.. This (-*- rst -*-) format file contains commonly used link targets and name
   substitutions.  It may be included in many files, therefore it should only
   contain link targets and name substitutions. Try grepping for "^\.\. _" to
   find plausible candidates for this list.

.. NOTE: reST targets are
   __not_case_sensitive__, so only one target definition is needed for:
   nipy, NIPY, Nipy, etc...


.. devices

.. _bistim²: https://www.magstim.com/us-en/magstim-bistim2/
.. _neuroconn dc-stimulator plus: https://www.neurocaregroup.com/technology/dc-stimulator-plus
.. _starstim 8: https://www.neuroelectrics.com/solutions/starstim/8/
.. _super rapid² plus¹: https://www.magstim.com/us-en/rapid2-family/

.. glossary

.. _LRPA: https://www.fieldtriptoolbox.org/faq/how_are_the_lpa_and_rpa_points_defined/
.. _Nasion: https://en.wikipedia.org/wiki/Nasion
.. _rst: https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html


.. others

.. _calpendo: https://campusbiotech.calpendo.com/


.. project

.. _MIT license: https://opensource.org/licenses/MIT
.. _project github: https://github.com/fcbg-hnp-meeg/nmod-wiki
.. _project github doc: https://github.com/fcbg-hnp-meeg/nmod-wiki/tree/main/doc
.. _project issue tracker: https://github.com/fcbg-hnp-meeg/nmod-wiki/issues
.. _project license: https://github.com/fcbg-hnp-meeg/nmod-wiki/blob/main/LICENSE


.. software

.. _pre-commit: https://pre-commit.com/
.. _sphinx-gallery: https://sphinx-gallery.github.io/stable/index.html
